"""initial schema

Revision ID: ef52ef0e70f4
Revises: 
Create Date: 2026-09-01 21:27:54.376905
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import backend.db.types

revision = 'ef52ef0e70f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bars',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('high >= low', name='ck_bars_high_ge_low'),
    sa.CheckConstraint('volume >= 0', name='ck_bars_volume_nonneg'),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.create_index('ix_bars_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('run_log',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('symbols_requested', sa.Integer(), nullable=False),
    sa.Column('symbols_ingested', sa.Integer(), nullable=False),
    sa.Column('bars_upserted', sa.Integer(), nullable=False),
    sa.Column('quarantined', backend.db.types.PortableJSON(), nullable=False),
    sa.Column('warnings', backend.db.types.PortableJSON(), nullable=False),
    sa.Column('repulled', backend.db.types.PortableJSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('run_log', schema=None) as batch_op:
        batch_op.create_index('ix_run_log_started', ['started_at'], unique=False)

    op.create_table('regime',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('dispersion_raw', sa.Float(), nullable=True),
    sa.Column('dispersion', sa.Float(), nullable=True),
    sa.Column('dispersion_percentile', sa.Float(), nullable=True),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.Column('low_dispersion', sa.Boolean(), nullable=False),
    sa.Column('benchmark_state', sa.String(length=24), nullable=True),
    sa.Column('benchmark_bars_in_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_log.run_id'], ),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('regime', schema=None) as batch_op:
        batch_op.create_index('ix_regime_date', ['date'], unique=False)

    op.create_table('rrg',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('rs', sa.Float(), nullable=True),
    sa.Column('rs_ratio', sa.Float(), nullable=True),
    sa.Column('rs_momentum', sa.Float(), nullable=True),
    sa.Column('quadrant', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['run_log.run_id'], ),
    sa.PrimaryKeyConstraint('symbol', 'date')
    )
    with op.batch_alter_table('rrg', schema=None) as batch_op:
        batch_op.create_index('ix_rrg_symbol_date', ['symbol', 'date'], unique=False)

    op.create_table('signals',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plane', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('term', backend.db.types.PortableJSON(), nullable=False),
    sa.Column('rvol', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('residual_close', sa.Float(), nullable=True),
    sa.Column('breadth_spread', sa.Float(), nullable=True),
    sa.Column('equal_weight_signal', sa.Float(), nullable=True),
    sa.Column('narrow', sa.Boolean(), nullable=False),
    sa.CheckConstraint("plane in ('absolute','relative')", name='ck_signals_plane'),
    sa.ForeignKeyConstraint(['run_id'], ['run_log.run_id'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'plane')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_date', ['date'], unique=False)
        batch_op.create_index('ix_signals_symbol_plane_date', ['symbol', 'plane', 'date'], unique=False)

    op.create_table('states',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plane', sa.String(length=16), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('bars_in_state', sa.Integer(), nullable=False),
    sa.Column('entered', sa.Boolean(), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('consec_above', sa.Integer(), nullable=False),
    sa.Column('consec_below', sa.Integer(), nullable=False),
    sa.CheckConstraint("plane in ('absolute','relative')", name='ck_states_plane'),
    sa.CheckConstraint('bars_in_state >= 0', name='ck_states_age_nonneg'),
    sa.ForeignKeyConstraint(['run_id'], ['run_log.run_id'], ),
    sa.PrimaryKeyConstraint('symbol', 'date', 'plane')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index('ix_states_entered', ['entered', 'date'], unique=False)
        batch_op.create_index('ix_states_symbol_plane_date', ['symbol', 'plane', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index('ix_states_symbol_plane_date')
        batch_op.drop_index('ix_states_entered')

    op.drop_table('states')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_symbol_plane_date')
        batch_op.drop_index('ix_signals_date')

    op.drop_table('signals')
    with op.batch_alter_table('rrg', schema=None) as batch_op:
        batch_op.drop_index('ix_rrg_symbol_date')

    op.drop_table('rrg')
    with op.batch_alter_table('regime', schema=None) as batch_op:
        batch_op.drop_index('ix_regime_date')

    op.drop_table('regime')
    with op.batch_alter_table('run_log', schema=None) as batch_op:
        batch_op.drop_index('ix_run_log_started')

    op.drop_table('run_log')
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_index('ix_bars_symbol_date')

    op.drop_table('bars')
    # ### end Alembic commands ###
